#!/usr/bin/env python3
"""OpenAPI single-source generator and drift gate (TASK-0023).

The hand-written ``specs/openapi/virtual-companion.yaml`` is the single source
of truth (ADR-0002). This tool deterministically generates a bundled OpenAPI
document plus a Java interface and a TypeScript client from it, and fails
closed when the generated artifacts drift from what is committed. Generation is
pure and deterministic — the same source always yields byte-identical output
(LF newlines, stable key order, fixed templates) — so the drift gate is exact.

It mirrors scripts/checks/catalog_tool.py but lives under scripts/dev/ and
writes to specs/openapi/dist/ so it does not collide with the catalog_tool-owned
specs/generated/ contract.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import shutil
import sys
import tempfile
from pathlib import Path
from typing import Any

import yaml

GENERATOR_VERSION = "1.0.0"
HEADER = "// GENERATED by openapi_tool.py; DO NOT EDIT.\n"


def repo_root() -> Path:
    return Path(__file__).resolve().parents[2]


def load_yaml(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path}: root must be an object")
    return data


def write_text_lf(path: Path, content: str) -> None:
    with path.open("w", encoding="utf-8", newline="\n") as handle:
        handle.write(content)


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def source_path(root: Path) -> Path:
    return root / "specs/openapi/virtual-companion.yaml"


def validate(root: Path) -> list[str]:
    errors: list[str] = []
    path = source_path(root)
    if not path.exists():
        return [f"missing OpenAPI source: {path.relative_to(root)}"]
    doc = load_yaml(path)
    if doc.get("openapi") != "3.1.0":
        errors.append("source: openapi must be 3.1.0")
    info = doc.get("info", {})
    if not info.get("title") or not info.get("version"):
        errors.append("source: info.title and info.version are required")
    schemas = doc.get("components", {}).get("schemas", {})
    envelope = schemas.get("ErrorEnvelope")
    if not isinstance(envelope, dict):
        errors.append("source: components.schemas.ErrorEnvelope is required")
    else:
        required = envelope.get("required", [])
        if "code" not in required or "message" not in required:
            errors.append("source: ErrorEnvelope must require code and message")
        props = envelope.get("properties", {})
        if "$ref" not in props.get("code", {}) and "enum" not in props.get("code", {}):
            if props.get("code", {}).get("$ref") != "#/components/schemas/ErrorCode":
                errors.append("source: ErrorEnvelope.code must reference ErrorCode")
    error_code = schemas.get("ErrorCode", {})
    if not isinstance(error_code, dict) or not error_code.get("enum"):
        errors.append("source: ErrorCode must be a string enum")
    if "NOT_FOUND_OR_FORBIDDEN" not in (error_code.get("enum") or []):
        errors.append("source: ErrorCode must include NOT_FOUND_OR_FORBIDDEN (existence hiding)")
    paths = doc.get("paths", {})
    if not paths:
        errors.append("source: at least one path is required")
    for p, item in paths.items():
        if not isinstance(item, dict):
            errors.append(f"source: path {p} must be an object")
            continue
        for method, op in item.items():
            if method == "parameters":
                continue
            if not isinstance(op, dict) or not op.get("operationId"):
                errors.append(f"source: {method.upper()} {p} must define operationId")
    return errors


def _record_name(schema_name: str) -> str:
    return schema_name


def generate(root: Path, out: Path) -> None:
    if out.exists():
        shutil.rmtree(out)
    doc = load_yaml(source_path(root))
    schemas = doc.get("components", {}).get("schemas", {})
    java_dir = out / "java/com/virtualcompanion/api"
    ts_dir = out / "typescript"
    for d in (java_dir, ts_dir):
        d.mkdir(parents=True, exist_ok=True)

    # Bundled OpenAPI: the source re-emitted with stable formatting so the drift
    # gate is exact (the source itself is the bundle for this self-contained
    # contract; no external $ref resolution is needed).
    write_text_lf(
        out / "api-bundle.yaml",
        yaml.safe_dump(doc, allow_unicode=True, sort_keys=False, width=120),
    )

    # Java ErrorCode enum.
    error_code_values = schemas["ErrorCode"]["enum"]
    constants = []
    for value in error_code_values:
        constant = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_").upper()
        constants.append(f'{constant}("{value}")')
    write_text_lf(
        java_dir / "ErrorCode.java",
        HEADER
        + "package com.virtualcompanion.api;\n\n"
        + "public enum ErrorCode {\n    "
        + ",\n    ".join(constants)
        + ";\n\n"
        + "    private final String code;\n\n"
        + "    ErrorCode(String code) { this.code = code; }\n\n"
        + "    public String code() { return code; }\n"
        + "}\n",
    )

    # Java records for object schemas (deterministic property order = source order).
    for name, schema in schemas.items():
        if name == "ErrorCode":
            continue
        if not isinstance(schema, dict) or schema.get("type") != "object":
            continue
        props = list(schema.get("properties", {}).keys())
        required = set(schema.get("required", []))
        fields = []
        for prop in props:
            java_type = "String"  # baseline: all properties are strings/JSON blobs
            fields.append(f"    final {java_type} {prop}")
        body = HEADER + "package com.virtualcompanion.api;\n\n"
        body += f"public record {name}(\n" + ",\n".join(fields) + "\n) {\n"
        body += f"    public {name} {{\n"
        for prop in props:
            if prop in required:
                body += f"        java.util.Objects.requireNonNull({prop}, \"{prop} must not be null\");\n"
            else:
                body += f"        // {prop} is nullable\n"
        body += "    }\n}\n"
        write_text_lf(java_dir / f"{name}.java", body)

    # Java interface: one method per operation, returning the 200-response record.
    method_lines = []
    for path, item in doc.get("paths", {}).items():
        for method, op in item.items():
            if method == "parameters" or not isinstance(op, dict):
                continue
            op_id = op.get("operationId")
            responses = op.get("responses", {})
            ok = responses.get("200", {})
            ref = (
                ok.get("content", {})
                .get("application/json", {})
                .get("schema", {})
                .get("$ref", "")
            )
            return_type = _record_name(ref.split("/")[-1]) if ref else "Void"
            method_lines.append(
                f"    /** {op.get('summary', op_id)}. */\n"
                f"    {return_type} {op_id}();"
            )
    write_text_lf(
        java_dir / "VirtualCompanionApi.java",
        HEADER
        + "package com.virtualcompanion.api;\n\n"
        + "public interface VirtualCompanionApi {\n"
        + "\n\n".join(method_lines)
        + "\n}\n",
    )

    # TypeScript client: stable types + one function per operation.
    ts = [HEADER.rstrip(), ""]
    ts.append(f"export const ErrorCodeValues = {error_code_values} as const")
    ts.append("export type ErrorCode = typeof ErrorCodeValues[number]")
    ts.append("")
    for name, schema in schemas.items():
        if name == "ErrorCode" or not isinstance(schema, dict) or schema.get("type") != "object":
            continue
        props = list(schema.get("properties", {}).keys())
        required = set(schema.get("required", []))
        fields = []
        for prop in props:
            opt = "" if prop in required else "?"
            fields.append(f"  {prop}{opt}: string")
        ts.append(f"export interface {name} {{")
        ts.extend(fields)
        ts.append("}")
        ts.append("")
    ts.append("export interface VirtualCompanionApiClient {")
    for path, item in doc.get("paths", {}).items():
        for method, op in item.items():
            if method == "parameters" or not isinstance(op, dict):
                continue
            # Same derivation as the Java interface: the 200-response $ref
            # names the return record; no JSON 200 body means void.
            responses = op.get("responses", {})
            ok = responses.get("200", {})
            ref = (
                ok.get("content", {})
                .get("application/json", {})
                .get("schema", {})
                .get("$ref", "")
            )
            return_type = _record_name(ref.split("/")[-1]) if ref else "void"
            ts.append(f"  {op['operationId']}(): Promise<{return_type}>")
    ts.append("}")
    write_text_lf(ts_dir / "api.ts", "\n".join(ts).rstrip() + "\n")

    # Snapshot for auditability.
    raw = source_path(root).read_bytes()
    snapshot = {
        "generatorVersion": GENERATOR_VERSION,
        "source": {"path": "specs/openapi/virtual-companion.yaml", "sha256": sha256_bytes(raw)},
        "operations": [
            op["operationId"]
            for item in doc.get("paths", {}).values() if isinstance(item, dict)
            for op in item.values() if isinstance(op, dict) and "operationId" in op
        ],
    }
    import json
    write_text_lf(
        out / "openapi.snapshot.json",
        json.dumps(snapshot, ensure_ascii=False, sort_keys=True, indent=2) + "\n",
    )


def file_map(path: Path) -> dict[str, bytes]:
    return {
        str(p.relative_to(path)): p.read_bytes()
        for p in sorted(path.rglob("*"))
        if p.is_file()
    }


def diff_generated(root: Path) -> list[str]:
    committed = root / "specs/openapi/dist"
    with tempfile.TemporaryDirectory() as td:
        tmp = Path(td) / "dist"
        generate(root, tmp)
        a = file_map(committed)
        b = file_map(tmp)
        diffs: list[str] = []
        for key in sorted(set(a) | set(b)):
            if key not in a:
                diffs.append(f"missing committed generated file: {key}")
            elif key not in b:
                diffs.append(f"unexpected committed generated file: {key}")
            elif a[key] != b[key]:
                diffs.append(f"generated drift: {key}")
        return diffs


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("command", choices=["validate", "generate", "diff"])
    ap.add_argument("--root", type=Path, default=repo_root())
    ap.add_argument("--output", type=Path)
    ap.add_argument("--fail-on-drift", action="store_true")
    args = ap.parse_args()
    root = args.root.resolve()
    errors = validate(root)
    if errors:
        for e in errors:
            print(f"ERROR: {e}", file=sys.stderr)
        return 1
    if args.command == "validate":
        print("OpenAPI validation: PASS")
        return 0
    if args.command == "generate":
        out = (args.output or root / "specs/openapi/dist").resolve()
        generate(root, out)
        print(f"Generated: {out}")
        return 0
    diffs = diff_generated(root)
    if diffs:
        for d in diffs:
            print(f"DRIFT: {d}", file=sys.stderr)
        return 1 if args.fail_on_drift else 0
    print("OpenAPI drift check: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
